version: 2
updates:
  # /.github/workflows/docker/*
  - package-ecosystem: docker
    directory: "/.github/workflows/docker"
    target-branch: 0.1.0
    schedule:
      interval: daily

  # /.devcontainer/Dockerfile
  - package-ecosystem: docker
    directory: "/.devcontainer"
    target-branch: 0.1.0
    schedule:
      interval: daily

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: 0.1.0
    schedule:
      interval: daily
