version: 2
updates:
  # /nginx/Dockerfile
  - package-ecosystem: docker
    directory: "/nginx"
    schedule:
      interval: daily

  # /www/Dockerfile
  - package-ecosystem: docker
    directory: "/www"
    schedule:
      interval: daily

  # /.github/workflows/docker/*
  - package-ecosystem: docker
    directory: "/.github/workflows/docker"
    schedule:
      interval: daily

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
