name: lava-cms

services:
  postgres:
    container_name: postgres
    image: postgres:16.1-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    entrypoint: docker-entrypoint.sh -c 'shared_buffers=256MB' -c 'max_connections=200'

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8.1
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

  nginx:
    container_name: nginx
    image: nginx:1.25.3-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    depends_on:
      - postgres
      - pgadmin

volumes:
  pgdata:
  pgadmin:
