name: lava

services:
  web:
    container_name: web
    build: ./www
    restart: always
    volumes:
      - /artifacts/playwright-report/:/app/admin/playwright-report/

  postgres:
    container_name: postgres
    image: postgres:15.1
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    depends_on:
      - web
    restart: always
