name: lava-cms

services:
  web:
    container_name: web
    build: ./www
    volumes:
      - /artifacts/playwright-report/:/app/admin/playwright-report/
      - /artifacts/api-report/:/app/admin/html/
    restart: always

  postgres:
    container_name: postgres
    image: postgres:15.3 # 15.3-alpine is very flaky in Github Actions
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    depends_on:
      - web
    restart: always
