name: lava-dev
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  web:
    # Uncomment if you want to override the service's Dockerfile to one in the .devcontainer
    # folder. Note that the path of the Dockerfile and context is relative to the *primary*
    # docker-compose.yml file (the first in the devcontainer.json "dockerComposeFile"
    # array). The sample below assumes your primary file is in the root of your project.
    #
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile

    environment:
      - DISPLAY=host.docker.internal:0

    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ./:/workspaces/lava-cms:cached
      - ~/.ssh:/home/ubuntu/.ssh
      - ~/.gitconfig:/home/ubuntu/.gitconfig
      - /tmp/.X11-unix:/tmp/.X11-unix
      - vscode:/home/ubuntu/.vscode-server
      - pnpm-store:/home/ubuntu/.pnpm-store

    # Uncomment the next four lines if you will use a ptrace-based debugger like C++, Go, and Rust.
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  vscode:
    external: true
  pnpm-store:
