name: lava-cms

services:
  web:
    container_name: web
    build:
      context: .
    volumes:
      - ../:/workspaces/lava-cms:cached
      - ~/.ssh:/home/pwuser/.ssh:cached
      - ~/.gitconfig:/home/pwuser/.gitconfig:cached
      - pnpm-store:/home/pwuser/.pnpm-store
      - ~/.config/nvim:/home/pwuser/.config/nvim
      - nvim:/home/pwuser/.local/share/nvim
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - 3000:3000
      - 3001:3001
    environment:
      - DISPLAY=:0
    command: /bin/sh -c "while sleep 1000; do :; done"
    restart: unless-stopped

  postgres:
    container_name: postgres
    image: postgres:15.3-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - pgdata:/var/lib/postgresql/data
    depends_on:
      - web
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:7.4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: always

  nginx:
    container_name: nginx
    image: nginx:1.25.1-alpine-slim
    ports:
      - "8080:80"
    volumes:
      - ../nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
      - postgres
      - pgadmin
    restart: always

volumes:
  pgdata:
  pgadmin:
  pnpm-store:
  nvim:
    external: true
