name: lava-cms-demo-reset

services:
  dump:
    container_name: dump
    build:
      context: ./dump/
      args:
        - DB_CONNECTION=${DB_CONNECTION}
    volumes:
      - ./mount:/app/mount

  restore:
    container_name: restore
    build:
      context: ./restore/
      args:
        - DB_CONNECTION=${DB_CONNECTION}
    volumes:
      - ./mount/:/app/mount
