name: Tests
on:
  pull_request:
    branches:
      - "**"
  workflow_dispatch:


jobs:
  admin-chromium:
    name: E2E test admin dashboard
    uses: ./.github/workflows/e2e.yaml
    with:
      browser: chromium

  admin-firefox:
    name: E2E test admin dashboard
    uses: ./.github/workflows/e2e.yaml
    with:
      browser: firefox

  admin-webkit:
    name: E2E test admin dashboard
    uses: ./.github/workflows/e2e.yaml
    with:
      browser: webkit

  api:
    name: Unit test API endpoints
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./www/admin

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.7.0
        with:
          node-version-file: ".nvmrc"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Setup pnpm cache
        uses: actions/cache@v3.3.1
        with:
          path: ${{ github.workspace }}/.pnpm-store/v3
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Test
        run: |
          pnpm prisma generate
          cp .env.test .env
          pnpm unit

      - name: Upload report
        uses: actions/upload-artifact@v3.1.2
        if: always()
        with:
          name: api-report
          path: ${{ github.workspace }}/www/admin/html
          retention-days: 30
