name: Playwright Tests
on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  admin-chromium:
    runs-on: ubuntu-22.04
    name: Test admin (Chromium)

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      # - name: Swap Dockerfiles
      #   run: mv .devcontainer/Dockerfile www/Dockerfile

      - name: Env files
        run: |
          echo "${{ secrets.ENV_ADMIN }}" > www/admin/.env
          echo "${{ secrets.ENV_API }}" > www/api/.env

      - name: Docker Layer Caching
        uses: satackey/action-docker-layer-caching@v0.0.11

      - name: Build
        run: docker compose build

      - name: Run
        run: docker compose up -d

      # - name: Wait for admin
      #   run: wget -qO- https://raw.githubusercontent.com/eficode/wait-for/$WAIT_FOR_VERSION/wait-for | sh -s -- http://localhost:3001/admin/api/health -t 0 -- echo "Admin is up and running"
      #   env:
      #     WAIT_FOR_VERSION: 4df3f9262d84cab0039c07bf861045fbb3c20ab7 # v2.2.3

      - name: Wait for admin
        run: sleep 60s

      - name: Test
        run: docker exec -w admin web pnpm test -- --project=chromium
