name: Playwright Tests
on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  admin-chromium:
    runs-on: ubuntu-22.04
    name: Test admin (Chromium)

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Swap Dockerfiles
        run: mv .github/workflows/Dockerfile www/Dockerfile

      - name: Env files
        run: |
          echo "${{ secrets.ENV_ADMIN }}" > www/admin/.env
          echo "${{ secrets.ENV_API }}" > www/api/.env

      - name: Docker Layer Caching
        uses: satackey/action-docker-layer-caching@v0.0.11

      - name: Build
        run: docker compose build

      - name: Run
        run: docker compose up -d

      - name: Wait for admin
        run: sleep 5s

      - name: Test
        run: docker exec -w /app/admin web pnpm test -- --project=chromium
